export const ARTICLE_MODEL = 'ARTICLE_MODEL';

export const USER_MODEL = 'USER_MODEL';

export const COURSE_MODEL = 'COURSE_MODEL';

export const UNFINISHED_COURSE_MODEL = 'UNFINISHED_COURSE_MODEL';

export const COURSE_EVALUATION = 'COURSE_EVALUATION';
